### ISSUE TITLE
Backend crash when opening hostile-named submission detail

### ISSUE THREAD

**Issue by issa-tseng** [getodk/central-backend#1157] opened 2024-06-19 01:19 UTC
1. Go to here: https://staging.getodk.cloud/#/projects/1/forms/'%3D%2B%2F*-451%25%2F%25/submissions
2. Open the submission detail page of any of the strangely named submissions
3. Server crash, user sees a 404

```
Problem [Error]: Could not find the resource you were looking for.
    at Object.result [as notFound] (lib/util/problem.js:45:31)
    at filterFields (lib/formats/odata.js:610:48)
    at lib/formats/odata.js:660:94
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
```

**Comment by lognaturel** [comment] 2024-06-19 03:47
It didn't ring a bell when you mentioned it but now I'm pretty sure this was @lindsay-stevens pushing the limits with `pyodk`. I think we discussed with @matthew-white and decided that we didn't need to support non-uuid instance ids. If that sounds right to everyone, I think we can close this!

**Comment by lognaturel** [comment] 2024-06-19 03:49
Well, could we surface the error and not do anything instead of crashing? Maybe that's not any easier than just supporting that case?

**Comment by alxndrsn** [comment] 2024-06-19 05:33
> we didn't need to support non-uuid instance ids

Should submissions with non-uuid instanceId values be rejected when initially submitted?

**Comment by issa-tseng** [comment] 2024-06-19 06:21
i'm not sure how the user input was inserted, but it feels like the hard crash should be addressed at least. bad input shouldn't crash the server, that's a DOS.

**Comment by alxndrsn** [comment] 2024-06-19 06:50
@issa-tseng where are you seeing the server crashing?  I'm seeing the 404, but having trouble recreating the crash.

**Comment by alxndrsn** [comment] 2024-06-19 10:27
It looks like the crash is caused by an unhandled error thrown by the synchronous call to `selectFields()` on line 52:

https://github.com/getodk/central-backend/blob/7afef66d7eb6c0e9844b7f3f67082a8e575835d0/lib/resources/odata.js#L49-L55

**Comment by issa-tseng** [comment] 2024-06-19 19:37
the crash happens without any parallel reqs for me. my guess is you need it because docker is restarting the server faster than you can see. i click the link once my server crashes 100% of the time.

**Comment by lognaturel** [comment] 2024-06-19 20:27
I want to be clear that I agree the crash should be prevented so glad to see #1158! I was also initially being fooled by the Docker restart.

**Closed** 2024-10-15 07:18 UTC
