### ISSUE TITLE
Refactor Form.createVersion function

### ISSUE THREAD

**Issue by sadiqkhoja** [getodk/central-backend#755] opened 2023-01-30 14:34 UTC
`Form.createVersion` is quite a lengthy function that is doing too much +

> The meaning of this arguments is unclear and is used in very specific circumstances (E.g. setting the encryption key or updating a form's version) and not how one might assume based on the name.
> We've added more logic to createVersion that is more thorough about checking for conflicts with previous versions and that doesn't need to run when some of these simpler updates happen.

**Comment by matthew-white** [comment] 2023-09-14 20:13
I'm going to go ahead and bump this to .5, since I'm still working on getting getodk/central#385 into .4, and we're close to the start of regression testing.

**Comment by matthew-white** [comment] 2023-11-28 05:17
@ktuite and I were chatting about this issue and concluded that it'd be OK to close it for now. It'd be nice to have this refactor, but we haven't gotten to it in almost a year, so it's clearly not pressing. We bumped it from v2023.4, and it looks like we won't get to it in v2023.5 either. If the refactor becomes a higher priority, we can always go ahead with it and/or reopen this issue.

**Closed by matthew-white** 2023-11-28 05:17 UTC
Labels: refactor
